import { describe, expect, it } from 'vitest';
import { DEFAULT_PALETTE, printerByKey, type Palette } from '../settings';
import type { MeshPart, Plate } from '../types';
import { APPLICATION, PROJECT_PATH, SETTINGS_PATH, writeBambuProject } from './bambu';
import { MODEL_PATH, preparePlates } from './common';
import { box, child, findAll, metadataValue, parseXml, part, plate, unzipText, type XmlNode } from './test-helpers';

const PALETTE: Palette = {
  ...DEFAULT_PALETTE,
  terrain: { hex: '#5C6161', line: 'PLA Basic' },
  buildings: { hex: '#FFFFFF', line: 'PLA Basic' },
  roads: { hex: '#FF0000', line: 'PLA Basic' },
};

async function write(plates: Plate[], printer = 'P1S', palette = PALETTE) {
  const files = await unzipText(writeBambuProject(preparePlates(plates, palette), printerByKey(printer)));
  return {
    files,
    model: parseXml(files[MODEL_PATH]),
    config: parseXml(files[SETTINGS_PATH]),
    project: JSON.parse(files[PROJECT_PATH]),
  };
}

function objects(model: XmlNode) {
  return findAll(model, 'object');
}

// Python writes a zero datum as "-0.000000" too. Adding 0 folds it to 0.
function translations(model: XmlNode): number[][] {
  return findAll(model, 'item').map((item) => item.attrs.transform.split(' ').map((v) => Number(v) + 0));
}

describe('writeBambuProject', () => {
  it('writes two plates with filaments, placement and the package parts', async () => {
    const terrain = part('terrain', 'Terrain', 'terrain', box(-100, -50, -3, 200, 100, 3));
    const buildings = part('buildings', 'Buildings', 'building', box(-10, -10, 0, 20, 20, 30));
    const roads = part('roads', 'Roads', 'road', box(-100, -1, 0, 200, 2, 0.6));
    const second = part('terrain', 'Terrain', 'terrain', box(0, 0, -1, 100, 100, 1));
    const { files, model, config, project } = await write([
      plate('Map', [terrain, buildings, roads], [-100, -50, 100, 50]),
      plate('Section R1 C2', [second], [0, 0, 100, 100]),
    ]);

    // The terrain is listed after the parts that reach into it, so it wins the overlap in the slicer.
    const objs = objects(model);
    expect(objs.map((o) => [o.attrs.id, o.attrs.name, o.attrs.type])).toEqual([
      ['1', 'Buildings', 'model'], ['2', 'Roads', 'model'], ['3', 'Terrain', 'model'], ['4', 'Map', 'model'],
      ['5', 'Terrain', 'model'], ['6', 'Section R1 C2', 'model'],
    ]);
    // Parts precede the assembly that references them, as 3MF requires.
    expect(objs.map((o) => findAll(o, 'component').map((c) => c.attrs.objectid))).toEqual([[], [], [], ['1', '2', '3'], [], ['5']]);
    const meta = (name: string) => findAll(model, 'metadata').find((m) => m.attrs.name === name)?.text;
    expect(meta('Application')).toBe(APPLICATION);
    expect(APPLICATION.startsWith('BambuStudio-')).toBe(true);
    expect(meta('BambuStudio:3mfVersion')).toBe('1');
    expect(meta('Description')).toBe('Generated by Jarvizar City Model');
    expect(meta('Copyright')).toBe('Map data © OpenStreetMap contributors, Overture Maps Foundation');
    const first = findAll(objs[2], 'vertex')[0].attrs;
    expect([first.x, first.y, first.z]).toEqual(['-100.000000', '-50.000000', '-3.000000']);
    expect(findAll(objs[2], 'triangle')).toHaveLength(12);
    expect(files[MODEL_PATH]).toContain('     <triangle v1="0" v2="2" v3="1"/>\n');
    expect(files[MODEL_PATH]).not.toContain('paint_color');

    // Plate one is centred by its bounds on the 256 mm bed and plate two on
    // the second virtual plate. Both share the datum of the lowest point.
    expect(findAll(model, 'item').map((i) => [i.attrs.objectid, i.attrs.printable])).toEqual([['4', '1'], ['6', '1']]);
    expect(translations(model)).toEqual([[1, 0, 0, 0, 1, 0, 0, 0, 1, 128, 128, 3], [1, 0, 0, 0, 1, 0, 0, 0, 1, 307.2 + 128 - 50, 128 - 50, 3]]);
    expect(files[MODEL_PATH]).toContain('transform="1 0 0 0 1 0 0 0 1 128.000000 128.000000 3.000000" printable="1"/>');

    // Filaments are one per colour in the model's order of first use, so the terrain is still 1.
    expect(project.filament_colour).toEqual(['#5C6161', '#FFFFFF', '#FF0000']);
    const settings = findAll(config, 'object').map((o) => [
      o.attrs.id, metadataValue(o, 'name'), metadataValue(o, 'extruder'),
      findAll(o, 'part').map((p) => [p.attrs.id, p.attrs.subtype, metadataValue(p, 'name'), metadataValue(p, 'extruder')]),
    ]);
    expect(settings).toEqual([
      ['4', 'Map', '1', [['1', 'normal_part', 'Buildings', '2'], ['2', 'normal_part', 'Roads', '3'], ['3', 'normal_part', 'Terrain', '1']]],
      ['6', 'Section R1 C2', '1', [['5', 'normal_part', 'Terrain', '1']]],
    ]);
    const plates = findAll(config, 'plate').map((p) => [
      metadataValue(p, 'plater_id'), metadataValue(p, 'plater_name'), metadataValue(p, 'locked'),
      metadataValue(child(p, 'model_instance')!, 'object_id'), metadataValue(child(p, 'model_instance')!, 'instance_id'),
      metadataValue(child(p, 'model_instance')!, 'identify_id'),
    ]);
    expect(plates).toEqual([['1', 'Map', 'false', '4', '0', '1'], ['2', 'Section R1 C2', 'false', '6', '0', '2']]);

    expect(project.printer_model).toBe('Bambu Lab P1S');
    expect(project.printer_settings_id).toBe('Bambu Lab P1S 0.4 nozzle');
    expect(project.print_settings_id).toBe('0.20mm Standard @BBL X1C');
    expect(project.printable_area).toEqual(['0x0', '256x0', '256x256', '0x256']);
    expect(project.printable_height).toBe('250');
    expect(project.filament_settings_id).toEqual(Array(3).fill('Bambu PLA Basic @BBL P1S 0.4 nozzle'));
    expect(project.filament_ids).toEqual(['GFA00', 'GFA00', 'GFA00']);
    expect(project.filament_type).toEqual(['PLA', 'PLA', 'PLA']);
    expect(project.filament_vendor).toEqual(['Bambu Lab', 'Bambu Lab', 'Bambu Lab']);
    expect(project.filament_diameter).toEqual(['1.75', '1.75', '1.75']);
    expect(project.flush_volumes_matrix).toEqual(['0', '280', '280', '280', '0', '280', '280', '280', '0']);
    expect(Object.keys(files).sort()).toEqual([MODEL_PATH, SETTINGS_PATH, PROJECT_PATH, '[Content_Types].xml', '_rels/.rels'].sort());
  });

  it('writes the package files exactly as the add-on did', async () => {
    const { files } = await write([plate('Map', [part('terrain', 'Terrain', 'terrain', box(0, 0, 0, 10, 10, 1))], [0, 0, 10, 10])]);
    expect(files['[Content_Types].xml']).toBe(
      '<?xml version="1.0" encoding="UTF-8"?>\n' +
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n' +
        ' <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n' +
        ' <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>\n' +
        ' <Default Extension="config" ContentType="application/xml"/>\n' +
        ' <Override PartName="/Metadata/project_settings.config" ContentType="application/json"/>\n' +
        '</Types>\n',
    );
    expect(files['_rels/.rels']).toBe(
      '<?xml version="1.0" encoding="UTF-8"?>\n' +
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n' +
        ' <Relationship Id="rel0" Target="/3D/3dmodel.model" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>\n' +
        '</Relationships>\n',
    );
    expect(files[MODEL_PATH].startsWith(
      '<?xml version="1.0" encoding="UTF-8"?>\n' +
        '<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" ' +
        'xmlns:BambuStudio="http://schemas.bambulab.com/package/2021">\n' +
        ' <metadata name="Application">BambuStudio-02.00.00.00</metadata>\n' +
        ' <metadata name="BambuStudio:3mfVersion">1</metadata>\n' +
        ' <metadata name="Description">Generated by Jarvizar City Model</metadata>\n' +
        ' <metadata name="Copyright">Map data © OpenStreetMap contributors, Overture Maps Foundation</metadata>\n' +
        ' <resources>\n' +
        '  <object id="1" name="Terrain" type="model">\n   <mesh>\n    <vertices>\n' +
        '     <vertex x="0.000000" y="0.000000" z="0.000000"/>\n',
    )).toBe(true);
    expect(files[MODEL_PATH].endsWith(
      '  <object id="2" name="Map" type="model">\n   <components>\n    <component objectid="1"/>\n   </components>\n  </object>\n' +
        ' </resources>\n <build>\n' +
        '  <item objectid="2" transform="1 0 0 0 1 0 0 0 1 123.000000 123.000000 -0.000000" printable="1"/>\n' +
        ' </build>\n</model>\n',
    )).toBe(true);
    // json.dumps(indent=2) layout.
    expect(files[PROJECT_PATH].startsWith('{\n  "name": "project_settings",\n  "version": "02.00.00.00",\n')).toBe(true);
    expect(files[PROJECT_PATH]).toContain('  "nozzle_diameter": [\n    "0.4"\n  ],\n');
    expect(files[SETTINGS_PATH]).toBe(
      '<?xml version="1.0" encoding="UTF-8"?>\n<config>\n' +
        ' <object id="2">\n  <metadata key="name" value="Map"/>\n  <metadata key="extruder" value="1"/>\n' +
        '  <part id="1" subtype="normal_part">\n   <metadata key="name" value="Terrain"/>\n' +
        '   <metadata key="extruder" value="1"/>\n  </part>\n </object>\n' +
        ' <plate>\n  <metadata key="plater_id" value="1"/>\n  <metadata key="plater_name" value="Map"/>\n' +
        '  <metadata key="locked" value="false"/>\n  <model_instance>\n' +
        '   <metadata key="object_id" value="2"/>\n   <metadata key="instance_id" value="0"/>\n' +
        '   <metadata key="identify_id" value="1"/>\n  </model_instance>\n </plate>\n</config>\n',
    );
  });

  it('changes layout and starting profiles with the bed', async () => {
    const terrain = part('terrain', 'Terrain', 'terrain', box(0, 0, 0, 100, 100, 2));
    const shifted = part('terrain', 'Terrain', 'terrain', box(100, 0, 0, 100, 100, 2));
    let { model, project } = await write(
      [plate('Section R1 C1', [terrain], [0, 0, 100, 100]), plate('Section R1 C2', [shifted], [100, 0, 200, 100])],
      'A1M',
    );
    expect(translations(model).map((t) => t.slice(9))).toEqual([[90 - 50, 90 - 50, 0], [216 + 90 - 150, 90 - 50, 0]]);
    expect(project.printable_area).toEqual(['0x0', '180x0', '180x180', '0x180']);
    expect(project.printable_height).toBe('180');
    expect(project.printer_model).toBe('Bambu Lab A1 mini');
    expect(project.print_settings_id).toBe('0.20mm Standard @BBL A1M');
    expect(project.filament_settings_id).toEqual(['Bambu PLA Basic @BBL A1M']);
    ({ model, project } = await write([plate('Map', [terrain], [0, 0, 100, 100])], 'H2D'));
    expect(project.printable_area).toEqual(['0x0', '350x0', '350x320', '0x320']);
    expect(project.printer_settings_id).toBe('Bambu Lab H2D 0.4 nozzle');
    expect(translations(model)[0].slice(9)).toEqual([175 - 50, 160 - 50, 0]);
    // A 2 x 2 grid: two columns, the second row one plate stride down.
    const four = [0, 1, 2, 3].map((i) => plate(`Section ${i}`, [terrain], [0, 0, 100, 100]));
    ({ model } = await write(four));
    const expected = [[78, 78], [307.2 + 78, 78], [78, 78 - 307.2], [307.2 + 78, 78 - 307.2]];
    translations(model).forEach((t, i) => {
      expect(t[9]).toBeCloseTo(expected[i][0], 6);
      expect(t[10]).toBeCloseTo(expected[i][1], 6);
    });
  });

  it('selects presets by filament line and numbers filaments per colour and line', async () => {
    const palette: Palette = {
      ...PALETTE,
      terrain: { hex: '#ffffff', line: 'PLA Matte' },
      buildings: { hex: '#AE835B', line: 'PLA Matte' },
      roads: { hex: '#545454', line: 'PLA Basic' },
      // The same colour in another line is another filament.
      paved: { hex: '#FFFFFF', line: 'PLA Basic' },
    };
    const mesh = box(0, 0, 0, 10, 10, 1);
    const parts = [
      part('terrain', 'Terrain', 'terrain', mesh),
      part('buildings', 'Buildings', 'building', mesh),
      part('roads', 'Roads', 'road', mesh),
      part('paved', 'Paved', 'paved', mesh),
      part('paths', 'Paths', 'path', mesh),
    ];
    const { config, project } = await write([plate('Map', parts, [0, 0, 10, 10])], 'P1S', palette);
    expect(project.filament_colour).toEqual(['#FFFFFF', '#AE835B', '#545454', '#FFFFFF']);
    expect(project.filament_settings_id).toEqual([
      'Bambu PLA Matte @BBL P1S 0.4 nozzle', 'Bambu PLA Matte @BBL P1S 0.4 nozzle',
      'Bambu PLA Basic @BBL P1S 0.4 nozzle', 'Bambu PLA Basic @BBL P1S 0.4 nozzle',
    ]);
    expect(project.filament_ids).toEqual(['GFA01', 'GFA01', 'GFA00', 'GFA00']);
    expect(project.flush_volumes_matrix).toHaveLength(16);
    // Listed with the terrain last, numbered in the model's order.
    expect(findAll(config, 'part').map((p) => metadataValue(p, 'extruder'))).toEqual(['2', '3', '4', '3', '1']);
    expect((await write([plate('Map', parts.slice(0, 1), [0, 0, 10, 10])], 'A1M', palette)).project.filament_settings_id).toEqual([
      'Bambu PLA Matte @BBL A1M',
    ]);
    const silk = { ...palette, terrain: { hex: '#FFFFFF', line: 'PLA Silk' } } as unknown as Palette;
    await expect(write([plate('Map', parts.slice(0, 1), [0, 0, 10, 10])], 'P1S', silk)).rejects.toThrow(/filament line/);
    const short = { ...palette, terrain: { hex: '#fff', line: 'PLA Basic' } } as Palette;
    await expect(write([plate('Map', parts.slice(0, 1), [0, 0, 10, 10])], 'P1S', short)).rejects.toThrow(/#RRGGBB/);
  });

  it('numbers repeated part names within a plate', async () => {
    const mesh = box(0, 0, 0, 1, 1, 1);
    const { model, config } = await write([
      plate('Map', [part('a', 'Buildings', 'building', mesh), part('b', 'Terrain', 'terrain', mesh), part('c', 'Buildings', 'building', mesh)], [0, 0, 1, 1]),
      plate('Section R1 C2', [part('a', 'Buildings', 'building', mesh)], [0, 0, 1, 1]),
    ]);
    expect(objects(model).map((o) => o.attrs.name)).toEqual(['Buildings 1', 'Buildings 2', 'Terrain', 'Map', 'Buildings', 'Section R1 C2']);
    expect(findAll(config, 'part').map((p) => metadataValue(p, 'name'))).toEqual(['Buildings 1', 'Buildings 2', 'Terrain', 'Buildings']);
  });

  it('escapes names', async () => {
    const mesh = box(0, 0, 0, 1, 1, 1);
    const { model, config, files } = await write([plate('Café "Map" & <co>', [part('a', 'Road\'s "A"', 'road', mesh)], [0, 0, 1, 1])]);
    expect(objects(model).map((o) => o.attrs.name)).toEqual(['Road\'s "A"', 'Café "Map" & <co>']);
    expect(metadataValue(findAll(config, 'plate')[0], 'plater_name')).toBe('Café "Map" & <co>');
    expect(files[MODEL_PATH]).toContain(`name='Café "Map" &amp; &lt;co&gt;'`);
  });

  it('streams large parts', async () => {
    const meshes = [];
    for (let i = 0; i < 6000; i++) meshes.push(box(i % 100, Math.floor(i / 100), 0, 0.5, 0.5, 1 + (i % 7)));
    const big = part('buildings', 'Buildings', 'building', ...meshes);
    const { files, model } = await write([plate('Map', [big], [0, 0, 100, 60])]);
    const obj = objects(model)[0];
    expect(findAll(obj, 'vertex')).toHaveLength(big.positions.length / 3);
    expect(findAll(obj, 'triangle')).toHaveLength(big.indices.length / 3);
    const last = findAll(obj, 'triangle').at(-1)!.attrs;
    expect([last.v1, last.v2, last.v3].map(Number)).toEqual([...big.indices.slice(-3)]);
    expect(files[MODEL_PATH].length).toBeGreaterThan(2 << 20);
  });

  it('rejects invalid parts and plates', async () => {
    const { positions, indices } = box(0, 0, 0, 1, 1, 1);
    const good = part('terrain', 'Terrain', 'terrain', { positions, indices });
    const bad: MeshPart[] = [
      { ...good, positions: new Float32Array([...positions.slice(0, -1), NaN]) },
      { ...good, positions: new Float32Array([...positions.slice(0, -1), Infinity]) },
      { ...good, indices: new Uint32Array() },
      { ...good, positions: new Float32Array() },
      { ...good, indices: new Uint32Array([...indices, 0, 1, 8]) },
      { ...good, indices: new Uint32Array([...indices, 0]) },
      { ...good, role: 'lava' as MeshPart['role'] },
    ];
    for (const part of bad) await expect(write([plate('Map', [part], [0, 0, 1, 1])])).rejects.toThrow(/Terrain/);
    await expect(write([])).rejects.toThrow(/at least one plate/);
    await expect(write([plate('Map', [], [0, 0, 1, 1])])).rejects.toThrow(/at least one part/);
    await expect(write([plate('Map', [good], [0, 0, NaN, 1])])).rejects.toThrow(/bounds/);
    const many = Array.from({ length: 37 }, (_, i) => plate(`Section R1 C${i + 1}`, [good], [0, 0, 1, 1]));
    await expect(write(many)).rejects.toThrow(/at most 36 plates/);
    expect((await write(many.slice(0, 36))).project.printer_model).toBe('Bambu Lab P1S');
    expect(() => writeBambuProject(preparePlates([plate('Map', [good], [0, 0, 1, 1])], PALETTE), printerByKey('MK4'))).toThrow(/no Bambu Studio presets/);
  });
});
