// Pieces shared by the 3MF and STL writers: part validation, filament
// numbering, part names, package files and streamed mesh objects.

import { COLOUR_GROUPS, type FilamentLine, type Palette, type PaletteEntry } from '../settings';
import { ROLE_GROUP, type ColourGroup, type MeshPart, type Plate } from '../types';
import { AsciiBuffer, asciiBytes, quoteattr } from './format';
import type { ZipEntry } from './zip';

export const APP_NAME = 'Jarvizar City Model';
export const DESCRIPTION = `Generated by ${APP_NAME}`;
// OpenStreetMap (ODbL) and Overture data require attribution on works made from them.
export const ATTRIBUTION = 'Map data © OpenStreetMap contributors, Overture Maps Foundation';

export const MIME_3MF = 'model/3mf';
export const MODEL_PATH = '3D/3dmodel.model';
export const CORE_NAMESPACE = 'http://schemas.microsoft.com/3dmanufacturing/core/2015/02';
const CONTENT_TYPES_NAMESPACE = 'http://schemas.openxmlformats.org/package/2006/content-types';
const RELATIONSHIPS_NAMESPACE = 'http://schemas.openxmlformats.org/package/2006/relationships';
const MODEL_RELATIONSHIP = 'http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel';
export const XML_HEADER = '<?xml version="1.0" encoding="UTF-8"?>\n';
export const CONFIG_CONTENT_TYPE = ' <Default Extension="config" ContentType="application/xml"/>\n';

// Bambu PLA lines and the filament_ids of their presets.
export const FILAMENT_IDS: Record<FilamentLine, string> = { 'PLA Basic': 'GFA00', 'PLA Matte': 'GFA01' };
const COLOUR = /^#[0-9A-F]{6}$/;

/** [Content_Types].xml for the .rels and .model parts, then `extra` Default or Override lines. */
export function contentTypes(extra = ''): string {
  return (
    XML_HEADER +
    `<Types xmlns="${CONTENT_TYPES_NAMESPACE}">\n` +
    ' <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n' +
    ' <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>\n' +
    extra +
    '</Types>\n'
  );
}

/** _rels/.rels with the one relationship, to the model. `attributes` come before its Type. */
export function modelRelationship(attributes = `Id="rel0" Target="/${MODEL_PATH}"`): string {
  return (
    XML_HEADER +
    `<Relationships xmlns="${RELATIONSHIPS_NAMESPACE}">\n` +
    ` <Relationship ${attributes} Type="${MODEL_RELATIONSHIP}"/>\n` +
    '</Relationships>\n'
  );
}

export interface Extents {
  minX: number;
  minY: number;
  minZ: number;
  maxX: number;
  maxY: number;
  maxZ: number;
}

function emptyExtents(): Extents {
  return { minX: Infinity, minY: Infinity, minZ: Infinity, maxX: -Infinity, maxY: -Infinity, maxZ: -Infinity };
}

function mergeExtents(into: Extents, other: Extents): void {
  into.minX = Math.min(into.minX, other.minX);
  into.minY = Math.min(into.minY, other.minY);
  into.minZ = Math.min(into.minZ, other.minZ);
  into.maxX = Math.max(into.maxX, other.maxX);
  into.maxY = Math.max(into.maxY, other.maxY);
  into.maxZ = Math.max(into.maxZ, other.maxZ);
}

export function triangleCount(part: MeshPart): number {
  return part.indices.length / 3;
}

/** Checks a part is a usable mesh and returns its extents. Errors name the part. */
function checkPart(part: MeshPart): Extents {
  const { name, positions, indices } = part;
  if (!positions.length || !indices.length) throw new Error(`${name}: a part needs vertices and triangles`);
  if (positions.length % 3 || indices.length % 3) {
    throw new Error(`${name}: vertices are (x, y, z) and triangles three vertex indices`);
  }
  let minX = Infinity;
  let minY = Infinity;
  let minZ = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  let maxZ = -Infinity;
  for (let i = 0; i < positions.length; i += 3) {
    const x = positions[i];
    const y = positions[i + 1];
    const z = positions[i + 2];
    // NaN or an infinity leaves NaN here.
    if (x - x + (y - y) + (z - z) !== 0) throw new Error(`${name}: nonfinite mesh coordinates`);
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
    if (z < minZ) minZ = z;
    if (z > maxZ) maxZ = z;
  }
  const count = positions.length / 3;
  for (let i = 0; i < indices.length; i++) {
    if (!(indices[i] < count)) throw new Error(`${name}: triangle references a missing vertex`);
  }
  return { minX, minY, minZ, maxX, maxY, maxZ };
}

function partGroup(part: MeshPart): ColourGroup {
  const group = ROLE_GROUP[part.role];
  if (!group) throw new Error(`${part.name}: unknown material role ${JSON.stringify(part.role)}`);
  return group;
}

export interface Filament {
  /** #RRGGBB, upper case. */
  hex: string;
  line: FilamentLine;
}

/** Filaments are one per distinct colour and line, numbered from 1 in order of first use. */
export class FilamentTable {
  readonly filaments: Filament[] = [];
  private readonly slots = new Map<string, number>();

  slot(entry: PaletteEntry): number {
    const hex = typeof entry.hex === 'string' ? entry.hex.toUpperCase() : '';
    if (!COLOUR.test(hex)) throw new Error(`Filament colours must be #RRGGBB: ${JSON.stringify(entry.hex)}`);
    if (!Object.hasOwn(FILAMENT_IDS, entry.line)) {
      throw new Error(`Unknown filament line: ${JSON.stringify(entry.line)}`);
    }
    const key = `${hex} ${entry.line}`;
    let slot = this.slots.get(key);
    if (slot === undefined) {
      this.filaments.push({ hex, line: entry.line });
      slot = this.filaments.length;
      this.slots.set(key, slot);
    }
    return slot;
  }
}

/** Repeated names are numbered in order: "Roads 1", "Roads 2". Unique names stay as they are. */
function numberedNames(names: string[]): string[] {
  const totals = new Map<string, number>();
  for (const name of names) totals.set(name, (totals.get(name) ?? 0) + 1);
  const counts = new Map<string, number>();
  return names.map((name) => {
    if (totals.get(name)! < 2) return name;
    const count = (counts.get(name) ?? 0) + 1;
    counts.set(name, count);
    return `${name} ${count}`;
  });
}

export interface PreparedPart {
  part: MeshPart;
  /** Numbered where a plate repeats a name. */
  name: string;
  extents: Extents;
  group: ColourGroup;
  colour: PaletteEntry;
}

export interface PreparedPlate {
  name: string;
  bounds: [number, number, number, number];
  parts: PreparedPart[];
  extents: Extents;
}

export interface PreparedModel {
  plates: PreparedPlate[];
  extents: Extents;
  /** The Copyright text: map data (unless the model used none), then any other sources the model used. */
  attribution: string;
}

/** Validates every plate and part up front, so a bad part fails before any output. */
export function preparePlates(plates: Plate[], palette: Palette, credits: string[] = [], mapData = true): PreparedModel {
  if (!plates.length) throw new Error('An export needs at least one plate');
  const extents = emptyExtents();
  const prepared = plates.map((plate): PreparedPlate => {
    const bounds = plate.bounds;
    if (!Array.isArray(bounds) || bounds.length !== 4 || !bounds.every(Number.isFinite) ||
        bounds[2] < bounds[0] || bounds[3] < bounds[1]) {
      throw new Error(`${plate.name}: plate bounds must be finite west, south, east, north`);
    }
    if (!plate.parts.length) throw new Error(`${plate.name}: a plate needs at least one part`);
    const names = numberedNames(plate.parts.map((part) => part.name.trim() || part.id || part.role));
    const plateExtents = emptyExtents();
    const parts = plate.parts.map((part, i): PreparedPart => {
      const partExtents = checkPart(part);
      mergeExtents(plateExtents, partExtents);
      const group = partGroup(part);
      const colour = palette[group];
      if (!colour) throw new Error(`${part.name}: the palette has no colour for ${group}`);
      return { part, name: names[i], extents: partExtents, group, colour };
    });
    mergeExtents(extents, plateExtents);
    return { name: plate.name, bounds: [...bounds], parts, extents: plateExtents };
  });
  return { plates: prepared, extents, attribution: [...(mapData ? [ATTRIBUTION] : []), ...credits].join('; ') };
}

export interface FilamentUse {
  filaments: Filament[];
  /** Filament number of every part, by plate. */
  slots: number[][];
  /** Labels of the colour groups each filament prints, in COLOUR_GROUPS order. */
  labels: string[][];
}

/** The model's filaments in order of first use and what each one prints. */
export function filamentUse(model: PreparedModel): FilamentUse {
  const table = new FilamentTable();
  const groups: Set<ColourGroup>[] = [];
  const slots = model.plates.map((plate) =>
    plate.parts.map((p) => {
      const slot = table.slot(p.colour);
      (groups[slot - 1] ??= new Set()).add(p.group);
      return slot;
    }),
  );
  const labels = groups.map((used) => COLOUR_GROUPS.filter((g) => used.has(g.key)).map((g) => g.label));
  return { filaments: table.filaments, slots, labels };
}

const VERTEX_START = asciiBytes('     <vertex x="');
const VERTEX_Y = asciiBytes('" y="');
const VERTEX_Z = asciiBytes('" z="');
const ROW_END = asciiBytes('"/>\n');
const TRIANGLE_START = asciiBytes('     <triangle v1="');
const TRIANGLE_V2 = asciiBytes('" v2="');
const TRIANGLE_V3 = asciiBytes('" v3="');

/** A 3MF model entry: markup as text, mesh rows as ASCII bytes, kept in order. */
export class ModelStream {
  private readonly ascii: AsciiBuffer;

  constructor(private readonly entry: ZipEntry) {
    this.ascii = new AsciiBuffer((chunk) => entry.bytes(chunk));
  }

  text(value: string): void {
    this.ascii.flush();
    this.entry.text(value);
  }

  /**
   * One mesh object. Several parts are concatenated: each part's vertices
   * follow the previous part's and its triangles are renumbered to match.
   */
  meshObject(id: number, name: string, parts: MeshPart[], attributes = ''): void {
    this.text(`  <object id="${id}" name=${quoteattr(name)} type="model"${attributes}>\n   <mesh>\n    <vertices>\n`);
    for (const part of parts) this.vertices(part.positions);
    this.text('    </vertices>\n    <triangles>\n');
    let offset = 0;
    for (const part of parts) {
      this.triangles(part.indices, offset);
      offset += part.positions.length / 3;
    }
    this.text('    </triangles>\n   </mesh>\n  </object>\n');
  }

  /** An object made of earlier objects, placed as they are. */
  assembly(id: number, name: string, components: number[]): void {
    this.text(`  <object id="${id}" name=${quoteattr(name)} type="model">\n   <components>\n`);
    this.text(components.map((component) => `    <component objectid="${component}"/>\n`).join(''));
    this.text('   </components>\n  </object>\n');
  }

  // Six decimals round-trip every float32 coordinate that matters for
  // printing, and both sides of a seam format the identical float.
  private vertices(positions: Float32Array): void {
    const out = this.ascii;
    for (let i = 0; i < positions.length; i += 3) {
      out.reserve(160);
      out.bytes(VERTEX_START);
      out.fixed6(positions[i]);
      out.bytes(VERTEX_Y);
      out.fixed6(positions[i + 1]);
      out.bytes(VERTEX_Z);
      out.fixed6(positions[i + 2]);
      out.bytes(ROW_END);
    }
  }

  private triangles(indices: Uint32Array, offset: number): void {
    const out = this.ascii;
    for (let i = 0; i < indices.length; i += 3) {
      out.reserve(80);
      out.bytes(TRIANGLE_START);
      out.int(indices[i] + offset);
      out.bytes(TRIANGLE_V2);
      out.int(indices[i + 1] + offset);
      out.bytes(TRIANGLE_V3);
      out.int(indices[i + 2] + offset);
      out.bytes(ROW_END);
    }
  }

  close(): void {
    this.ascii.flush();
    this.entry.close();
  }
}
