import { describe, expect, it } from 'vitest';
import { DEFAULT_PALETTE, printerByKey, type Palette, type Printer } from '../settings';
import type { Plate } from '../types';
import { MODEL_PATH, preparePlates } from './common';
import { box, findAll, parseXml, part, plate, unzipText } from './test-helpers';
import { writeGeneric3mf } from './threemf';

async function write(plates: Plate[], palette: Palette, printer: Printer, title?: string) {
  const files = await unzipText(writeGeneric3mf(preparePlates(plates, palette), printer, title));
  return { files, model: parseXml(files[MODEL_PATH]) };
}

function translation(transform: string): number[] {
  return transform.split(' ').slice(9).map((v) => Number(v) + 0);
}

describe('writeGeneric3mf', () => {
  const terrain = part('terrain', 'Terrain', 'terrain', box(-50, -40, -2, 100, 80, 2));
  const roads = part('roads', 'Roads', 'road', box(-50, -1, -0.15, 100, 2, 0.6));
  const paved = part('paved', 'Paved', 'paved', box(0, 0, -0.15, 10, 10, 0.5));
  const buildings = part('buildings', 'Buildings', 'building', box(-10, -10, 0, 5, 5, 20), box(10, 10, 0, 4, 4, 8));

  it('gives each colour a base material and each part an object with it', async () => {
    const { files, model } = await write([plate('Map', [terrain, roads, paved, buildings], [-50, -40, 50, 40])], DEFAULT_PALETTE, printerByKey('P1S'), 'Chicago Loop');
    const bases = findAll(model, 'base').map((b) => [b.attrs.name, b.attrs.displaycolor]);
    // Roads and paving share Ash Gray in the default palette.
    expect(bases).toEqual([
      ['PLA Matte Ivory White', '#FFFFFFFF'],
      ['PLA Matte Ash Gray', '#9B9EA0FF'],
      ['PLA Matte Caramel', '#AE835BFF'],
    ]);
    expect(findAll(model, 'basematerials').map((m) => m.attrs.id)).toEqual(['1']);
    const objects = findAll(model, 'object');
    expect(objects.map((o) => [o.attrs.id, o.attrs.name, o.attrs.pid, o.attrs.pindex])).toEqual([
      ['2', 'Terrain', '1', '0'], ['3', 'Roads', '1', '1'], ['4', 'Paved', '1', '1'], ['5', 'Buildings', '1', '2'],
      ['6', 'Map', undefined, undefined],
    ]);
    expect(findAll(objects[4], 'component').map((c) => c.attrs.objectid)).toEqual(['2', '3', '4', '5']);
    expect(findAll(objects[3], 'triangle')).toHaveLength(24);
    const meta = Object.fromEntries(findAll(model, 'metadata').map((m) => [m.attrs.name, m.text]));
    expect(meta).toEqual({
      Title: 'Chicago Loop',
      Application: 'Jarvizar City Model',
      Description: 'Generated by Jarvizar City Model',
      Copyright: 'Map data © OpenStreetMap contributors, Overture Maps Foundation',
    });
    // One build item: centred on the bed, lowest point on it.
    const items = findAll(model, 'item');
    expect(items.map((i) => i.attrs.objectid)).toEqual(['6']);
    expect(translation(items[0].attrs.transform)).toEqual([128, 128, 2]);
    expect(Object.keys(files).sort()).toEqual(['3D/3dmodel.model', '[Content_Types].xml', '_rels/.rels']);
    expect(files['[Content_Types].xml']).not.toContain('config');
    expect(files['_rels/.rels']).toContain('Target="/3D/3dmodel.model"');
  });

  it('lays sections out in their grid, 10 mm apart, centred on the bed', async () => {
    const cells: [number, number, number, number][] = [[-50, 0, 0, 40], [0, 0, 50, 40], [-50, -40, 0, 0], [0, -40, 50, 0]];
    const plates = cells.map((bounds, i) =>
      plate(`Section R${i < 2 ? 1 : 2} C${(i % 2) + 1}`, [part('terrain', 'Terrain', 'terrain', box(bounds[0], bounds[1], -2, 50, 40, 2))], bounds),
    );
    const { model } = await write(plates, DEFAULT_PALETTE, printerByKey('A1M'));
    const items = findAll(model, 'item').map((i) => translation(i.attrs.transform));
    // The exploded layout is 110 x 90 mm, centred on the 180 mm bed.
    expect(items).toEqual([[85, 95, 2], [95, 95, 2], [85, 85, 2], [95, 85, 2]]);
    const placed = plates.map((p, i) => [p.bounds[0] + items[i][0], p.bounds[1] + items[i][1], p.bounds[2] + items[i][0], p.bounds[3] + items[i][1]]);
    expect(placed).toEqual([[35, 95, 85, 135], [95, 95, 145, 135], [35, 45, 85, 85], [95, 45, 145, 85]]);
  });
});
