"""Native, unsliced Bambu Studio projects written directly from mesh arrays.

No slicer dependency, external 3MF writer, or copied project template. Plate
records and build transforms follow Bambu's PartPlateList; each part's
filament is its model_settings ``extruder``, and bbs_3mf/FacetsAnnotation
triangle paint marks only the minority materials of a part that mixes them.
The Bambu application marker selects its native project loader (otherwise
it discards project configuration). Creator metadata identifies our exporter.
"""

from collections import Counter
from dataclasses import dataclass
import json
import math
import re
from xml.sax.saxutils import quoteattr
import zipfile

from .export_3mf import CORE, MODEL, SETTINGS
from .export_sections import BAMBU_MAX_PLATES, plate_origin


PROJECT = "Metadata/project_settings.config"
BAMBU_NAMESPACE = "http://schemas.bambulab.com/package/2021"
# Bambu gates project loading on this Application prefix; version 2.0 also
# avoids its pre-1.5.9 bed-offset and pre-2.0 prime-volume migrations.
APPLICATION = "BambuStudio-02.00.00.00"
DESCRIPTION = "Generated by Jarvizar City Model"
DEFAULT_COLOR = "#FFFFFF"
# Blender meshes are float32: six decimals round-trip every printable
# coordinate, and both sides of a seam format the identical float.
_VERTEX = '     <vertex x="%.6f" y="%.6f" z="%.6f"/>\n'
_TRIANGLE = '     <triangle v1="%d" v2="%d" v3="%d"%s/>\n'
_CHUNK = 65536
_COLOR = re.compile(r"^#[0-9A-F]{6}$")
_CONTENT_NS = "http://schemas.openxmlformats.org/package/2006/content-types"
_REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"


@dataclass(frozen=True)
class BambuPrinter:
    """Bed and starting presets, as named in Bambu Studio's bundled profiles."""

    key: str
    model: str
    width: float
    depth: float
    height: float
    print_profile: str
    filament_profile: str
    filament_id: str = "GFA00"  # Bambu PLA Basic
    filament_vendor: str = "Bambu Lab"
    filament_type: str = "PLA"

    @property
    def printer_profile(self):
        return f"{self.model} 0.4 nozzle"

    @property
    def bed(self):
        return f"{self.width:g} x {self.depth:g} mm"


# Machine profiles: printable_area, printable_height, default_print_profile
# and default_filament_profile of each "<model> 0.4 nozzle" preset.
PRINTERS = {printer.key: printer for printer in (
    BambuPrinter("A1M", "Bambu Lab A1 mini", 180, 180, 180,
                 "0.20mm Standard @BBL A1M", "Bambu PLA Basic @BBL A1M"),
    BambuPrinter("A1", "Bambu Lab A1", 256, 256, 256,
                 "0.20mm Standard @BBL A1", "Bambu PLA Basic @BBL A1"),
    BambuPrinter("P1P", "Bambu Lab P1P", 256, 256, 250,
                 "0.20mm Standard @BBL P1P", "Bambu PLA Basic @BBL P1P"),
    BambuPrinter("P1S", "Bambu Lab P1S", 256, 256, 250,
                 "0.20mm Standard @BBL X1C", "Bambu PLA Basic @BBL P1S 0.4 nozzle"),
    BambuPrinter("P2S", "Bambu Lab P2S", 256, 256, 256,
                 "0.20mm Standard @BBL P2S", "Bambu PLA Basic @BBL P2S"),
    BambuPrinter("X1C", "Bambu Lab X1 Carbon", 256, 256, 250,
                 "0.20mm Standard @BBL X1C", "Bambu PLA Basic @BBL X1C"),
    BambuPrinter("X1E", "Bambu Lab X1E", 256, 256, 250,
                 "0.20mm Standard @BBL X1C", "Bambu PLA Basic @BBL X1C"),
    BambuPrinter("X2D", "Bambu Lab X2D", 256, 256, 261,
                 "0.20mm Standard @BBL X2D", "Bambu PLA Basic @BBL X2D 0.4 nozzle"),
    BambuPrinter("A2L", "Bambu Lab A2L", 330, 320, 325,
                 "0.20mm Standard @BBL A2L", "Bambu PLA Basic @BBL A2L 0.4 nozzle"),
    BambuPrinter("H2C", "Bambu Lab H2C", 330, 320, 325,
                 "0.20mm Standard @BBL H2C", "Bambu PLA Basic @BBL H2C"),
    BambuPrinter("H2S", "Bambu Lab H2S", 340, 320, 340,
                 "0.20mm Standard @BBL H2S", "Bambu PLA Basic @BBL H2S"),
    BambuPrinter("H2D", "Bambu Lab H2D", 350, 320, 325,
                 "0.20mm Standard @BBL H2D", "Bambu PLA Basic @BBL H2D"),
    BambuPrinter("H2DP", "Bambu Lab H2D Pro", 350, 320, 325,
                 "0.20mm Standard @BBL H2DP", "Bambu PLA Basic @BBL H2DP"),
)}
DEFAULT_PRINTER = "P1S"
MAX_BED_DIMENSION = max(max(printer.width, printer.depth) for printer in PRINTERS.values())


def _paint(extruder):
    # An unsplit triangle: two zero split bits, then its extruder state.
    # States >= 3 extend the C nibble by base-15 continuation nibbles.
    if extruder < 3:
        return f"{extruder * 4:X}"
    value = extruder - 3
    return f"{value % 15:X}" + "F" * (value // 15) + "C"


class PlateWriter:
    """Stream plates into one native Bambu project.

    Geometry is written to the model file as it arrives and never kept, so
    memory is bounded by the largest part rather than the project. Filaments
    are one per distinct colour, in order of first use; every part is assigned
    the filament of its most common material, and triangles of any other
    material carry Bambu's paint state for theirs. All plates share one Z
    datum: the lowest point of the whole model rests on the bed.
    """

    def __init__(self, model_path, printer):
        self.printer = printer
        self.palette = []
        self._filaments = {}
        self._plates = []
        self._next_id = 1
        self._bottom = math.inf
        self._model_path = model_path
        self._model = open(model_path, "w", encoding="utf-8", newline="\n")
        self._model.write(
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<model unit="millimeter" xml:lang="en-US" xmlns="{CORE}" xmlns:BambuStudio="{BAMBU_NAMESPACE}">\n'
            f' <metadata name="Application">{APPLICATION}</metadata>\n'
            ' <metadata name="BambuStudio:3mfVersion">1</metadata>\n'
            f' <metadata name="Description">{DESCRIPTION}</metadata>\n'
            ' <resources>\n')

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self._model.close()
        return False

    @property
    def plate_count(self):
        return len(self._plates)

    def filament(self, color):
        if not isinstance(color, str) or not _COLOR.match(color):
            raise ValueError(f"Filament colours must be #RRGGBB: {color!r}")
        if color not in self._filaments:
            self.palette.append(color)
            self._filaments[color] = len(self.palette)
        return self._filaments[color]

    def add_plate(self, name, parts, bounds=None):
        """Add one plate: an assembly of named parts placed on its own bed.

        ``parts`` yields (name, vertices, triangles, materials, colors): vertex
        rows (x, y, z) in model millimetres, triangle rows of three vertex
        indices, one material index per triangle, and the "#RRGGBB" colour of
        each material index. Parts are written as they arrive. ``bounds``
        (west, south, east, north) centre the plate; by default its contents.
        """
        if len(self._plates) >= BAMBU_MAX_PLATES:
            raise ValueError(f"Bambu Studio supports at most {BAMBU_MAX_PLATES} plates")
        extents = [math.inf, math.inf, -math.inf, -math.inf]
        entries = []
        for part_name, vertices, triangles, materials, colors in parts:
            entries.append(self._write_part(part_name, vertices, triangles, materials, colors, extents))
        if not entries:
            raise ValueError(f"{name}: a plate needs at least one part")
        assembly = self._next_id
        self._next_id += 1
        write = self._model.write
        write(f'  <object id="{assembly}" name={quoteattr(name)} type="model">\n   <components>\n')
        for part_id, _, _ in entries:
            write(f'    <component objectid="{part_id}"/>\n')
        write('   </components>\n  </object>\n')
        self._plates.append((name, tuple(extents if bounds is None else bounds), assembly, entries))
        return assembly

    def _write_part(self, name, vertices, triangles, materials, colors, extents):
        filaments = [self.filament(color) for color in colors]
        if not filaments:
            raise ValueError(f"{name}: a part needs at least one material colour")
        rows = [tuple(vertex) for vertex in vertices]
        faces = [tuple(triangle) for triangle in triangles]
        materials = list(materials)
        if not rows or not faces:
            raise ValueError(f"{name}: a part needs vertices and triangles")
        if len(materials) != len(faces):
            raise ValueError(f"{name}: one material index per triangle is required")
        if any(len(row) != 3 for row in rows) or any(len(face) != 3 for face in faces):
            raise ValueError(f"{name}: vertices are (x, y, z) and triangles three vertex indices")
        xs, ys, zs = zip(*rows)
        if not all(all(map(math.isfinite, values)) for values in (xs, ys, zs)):
            raise ValueError(f"{name}: nonfinite mesh coordinates")
        if min(map(min, faces)) < 0 or max(map(max, faces)) >= len(rows):
            raise ValueError(f"{name}: triangle references a missing vertex")
        counts = Counter(materials)
        if any(not 0 <= index < len(filaments) for index in counts):
            raise ValueError(f"{name}: material index without a colour")
        extents[0], extents[1] = min(extents[0], min(xs)), min(extents[1], min(ys))
        extents[2], extents[3] = max(extents[2], max(xs)), max(extents[3], max(ys))
        self._bottom = min(self._bottom, min(zs))
        # The most common material is the part's filament; ties keep the
        # lowest slot. Paint only triangles whose filament differs from it.
        default = filaments[max(counts, key=lambda index: (counts[index], -index))]
        suffix = {index: "" if filaments[index] == default else f' paint_color="{_paint(filaments[index])}"'
                  for index in counts}
        part_id = self._next_id
        self._next_id += 1
        write = self._model.write
        write(f'  <object id="{part_id}" name={quoteattr(name)} type="model">\n   <mesh>\n    <vertices>\n')
        for start in range(0, len(rows), _CHUNK):
            write("".join(map(_VERTEX.__mod__, rows[start:start + _CHUNK])))
        write('    </vertices>\n    <triangles>\n')
        painted = [(a, b, c, suffix[index]) for (a, b, c), index in zip(faces, materials)]
        for start in range(0, len(painted), _CHUNK):
            write("".join(map(_TRIANGLE.__mod__, painted[start:start + _CHUNK])))
        write('    </triangles>\n   </mesh>\n  </object>\n')
        return part_id, name, default

    def close(self, destination):
        """Finish the model and write the complete project archive."""
        if self._model.closed:
            raise ValueError("The project has already been written")
        if not self._plates:
            raise ValueError("A Bambu project needs at least one plate")
        printer = self.printer
        count = len(self._plates)
        write = self._model.write
        write(' </resources>\n <build>\n')
        for index, (name, bounds, assembly, entries) in enumerate(self._plates):
            west, south, east, north = bounds
            ox, oy = plate_origin(index, count, printer.width, printer.depth)
            tx = ox + printer.width / 2 - (west + east) / 2
            ty = oy + printer.depth / 2 - (south + north) / 2
            write(f'  <item objectid="{assembly}" transform="1 0 0 0 1 0 0 0 1 '
                  f'{tx:.6f} {ty:.6f} {-self._bottom:.6f}" printable="1"/>\n')
        write(' </build>\n</model>\n')
        self._model.close()

        config = ['<?xml version="1.0" encoding="UTF-8"?>\n<config>\n']
        for name, bounds, assembly, entries in self._plates:
            config.append(f' <object id="{assembly}">\n  <metadata key="name" value={quoteattr(name)}/>\n'
                          f'  <metadata key="extruder" value="{entries[0][2]}"/>\n')
            for part_id, part_name, extruder in entries:
                config.append(f'  <part id="{part_id}" subtype="normal_part">\n'
                              f'   <metadata key="name" value={quoteattr(part_name)}/>\n'
                              f'   <metadata key="extruder" value="{extruder}"/>\n  </part>\n')
            config.append(' </object>\n')
        for index, (name, bounds, assembly, entries) in enumerate(self._plates):
            config.append(f' <plate>\n  <metadata key="plater_id" value="{index + 1}"/>\n'
                          f'  <metadata key="plater_name" value={quoteattr(name)}/>\n'
                          '  <metadata key="locked" value="false"/>\n  <model_instance>\n'
                          f'   <metadata key="object_id" value="{assembly}"/>\n'
                          '   <metadata key="instance_id" value="0"/>\n'
                          f'   <metadata key="identify_id" value="{index + 1}"/>\n'
                          '  </model_instance>\n </plate>\n')
        config.append('</config>\n')

        filaments = len(self.palette)
        width, depth = f"{printer.width:g}", f"{printer.depth:g}"
        project = {
            "name": "project_settings",
            "version": "02.00.00.00",
            "printer_model": printer.model,
            "printer_settings_id": printer.printer_profile,
            "print_settings_id": printer.print_profile,
            "printer_technology": "FFF",
            "nozzle_diameter": ["0.4"],
            "printable_area": ["0x0", f"{width}x0", f"{width}x{depth}", f"0x{depth}"],
            "printable_height": f"{printer.height:g}",
            "filament_colour": list(self.palette),
            "filament_settings_id": [printer.filament_profile] * filaments,
            "filament_ids": [printer.filament_id] * filaments,
            "filament_vendor": [printer.filament_vendor] * filaments,
            "filament_type": [printer.filament_type] * filaments,
            "filament_diameter": ["1.75"] * filaments,
            # A square matrix is required by the native project loader. This is
            # the standard 140 mm^3 unload + 140 mm^3 load starting allowance;
            # Bambu's Flushing Volumes dialog can recalculate for actual filaments.
            "flush_volumes_matrix": ["0" if a == b else "280"
                                     for a in range(filaments) for b in range(filaments)],
        }
        # Bambu matches the literal OPC tag names, so each XML part carries its
        # own default namespace. The project holds no thumbnails or external
        # models; declare precisely its parts.
        types = ('<?xml version="1.0" encoding="UTF-8"?>\n'
                 f'<Types xmlns="{_CONTENT_NS}">\n'
                 ' <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n'
                 ' <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>\n'
                 ' <Default Extension="config" ContentType="application/xml"/>\n'
                 f' <Override PartName="/{PROJECT}" ContentType="application/json"/>\n'
                 '</Types>\n')
        relationships = ('<?xml version="1.0" encoding="UTF-8"?>\n'
                         f'<Relationships xmlns="{_REL_NS}">\n'
                         f' <Relationship Id="rel0" Target="/{MODEL}" '
                         'Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>\n'
                         '</Relationships>\n')
        with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.write(self._model_path, MODEL)
            archive.writestr(SETTINGS, "".join(config))
            archive.writestr("[Content_Types].xml", types)
            archive.writestr(PROJECT, json.dumps(project, indent=2))
            archive.writestr("_rels/.rels", relationships)
